# HTTP-specific options.
http:

  # The port on which the HTTP server listens for service requests.
  port: 8080

  # The type of connector to use. Other valid values are "nonblocking" or "legacy". In general, the
  # blocking connector should be used for low-latency services with short request durations. The
  # nonblocking connector should be used for services with long request durations or which
  # specifically take advantage of Jetty's continuation support.
  # If you need SSL support, you can either choose from "nonblocking+ssl" or "legacy+ssl".
  connectorType: blocking
  
  # HTTP request log settings.
  requestLog:

    # Settings for logging to stdout.
    console:

      # If true, log requests to stdout.
      enabled: false
  # SSL
  #ssl:
  #  keyStore: ./example.keystore
  #  keyStorePassword: example
      
 # Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

config:

  # Environment
  env: dev

  # The hello message to display at http://localhost:9898/hello
  message: Welcome to the hello application !!!
  
  # Urban Airship API key
  urbanAirshipApiKey: KXhrEtypS1Or_NIe5F4rkA
  
  # Urban Airship API secret
  urbanAirshipApiSecret: L7CHzQ-pQBKNWsuuJVsu6w
  
  # Urban Airship Root Path
  urbanAirshipRootPath: https://go.urbanairship.com/api